### 9-MARKS PROGRAM

In [4]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

with open("30 Most Popular Movies.html","r",encoding="utf-8") as file:
    content = file.read()
soup = BeautifulSoup(content, 'html.parser')
movie_names = []
movie_ratings = []

movies = soup.find_all('div', class_='article_movie_title')
for movie in movies:
    name = movie.find('a').text.strip()
    movie_names.append(name)
    rating = movie.find('span', class_='tMeterScore').text.strip()
    movie_ratings.append(rating)
data = {
    "Movie Name": movie_names,
    "Rating": movie_ratings
}

df = pd.DataFrame(data)
df

                                 Movie Name Rating
0          Transformers: Rise of the Beasts    53%
1       Spider-Man: Across the Spider-Verse    96%
2                        The Little Mermaid    67%
3                             The Boogeyman    63%
4     Are You There God? It's Me, Margaret.    99%
5                                    Fast X    56%
6                                BlackBerry    98%
7                               The Machine    27%
8                                   Reality    92%
9                               Flamin' Hot    68%
10           Guardians of the Galaxy Vol. 3    82%
11                                Blue Jean    94%
12                               Past Lives    97%
13              The Super Mario Bros. Movie    58%
14                 Avatar: The Way of Water    76%
15               Guy Ritchie's The Covenant    83%
16                                Bumblebee    91%
17                                Nefarious    33%
18                                     Sisu    93%
19                     You Hurt My Feelings    95%
20                     John Wick: Chapter 4    94%
21                           Leave No Trace    80%
22                          About My Father    36%
23  Dungeons & Dragons: Honor Among Thieves    90%
24                             Transformers    57%
25                                 My Fault
26                         A Beautiful Life    50%
27     The Angry Black Girl and Her Monster    88%
28                                  Missing    87%
29                                      Air    92%

## NEW TASK

make dataframe
column1=carname
coulmn2=mileage
column3=price
column4=rating

In [10]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

with open("Certified used Mercedes-Benz for sale.html","r",encoding="utf-8") as file:
    content = file.read()
soup = BeautifulSoup(content, 'html.parser')
car_names = []
car_mileage = []
car_price=[]
car_ratings = []

products = soup.find_all('div', class_='vehicle-details')
for product in products:
    car_names.append(product.find('h2', class_='title').text.strip())
    car_mileage.append(product.find('div', class_='mileage').text.strip())
    car_price.append(product.find('span', class_='primary-price').text.strip())
    
    rating_tag = product.find('span', class_='sds-rating__count')
    if rating_tag:
        car_ratings.append(rating_tag.text.strip())
    else:
        car_ratings.append("N/A")

data = {
    "Car Name": car_names,
    "Car Mileage": car_mileage,
    "Car Price": car_price,
    "Car Rating": car_ratings
}

df = pd.DataFrame(data)
df

,Car Name,Car Mileage,Car Price,Car Rating
0,2020 Mercedes-Benz CLA 250 Base 4MATIC,"28,744 mi.","$35,995",4.4
1,2019 Mercedes-Benz AMG GT 53 Base,"25,771 mi.","$79,995",4.0
2,2021 Mercedes-Benz AMG GLE 53 Base,"22,374 mi.","$80,923",2.8
3,2022 Mercedes-Benz AMG CLA 45 Base 4MATIC,"10,595 mi.","$56,633",N/A
4,2021 Mercedes-Benz AMG GLE 53 Base,"33,622 mi.","$76,995",4.7
5,2021 Mercedes-Benz E-Class E 450 4MATIC,"12,477 mi.","$76,532",4.5
6,2021 Mercedes-Benz AMG GLE 63 S-Model 4MATIC,"22,383 mi.","$102,990",4.8
7,2019 Mercedes-Benz S-Class S 560,"49,332 mi.","$54,580",4.8
8,2021 Mercedes-Benz AMG GLE 53 Base,"37,688 mi.","$76,715",2.8
9,2021 Mercedes-Benz GLA 250 Base,"19,521 mi.","$34,999",4.6
10,2022 Mercedes-Benz AMG C 43 Base 4MATIC,"14,420 mi.","$62,991",4.8
11,2018 Mercedes-Benz AMG C 43 Base 4MATIC,"34,555 mi.","$39,999",4.4
12,2021 Mercedes-Benz E-Class E 450 4MATIC,"16,474 mi.","$74,998",4.8
13,2021 Mercedes-Benz S-Class S 580 4MATIC,"10,233 mi.","$99,822",4.5
14,2022 Mercedes-Benz GLE 450 AWD 4MATIC,"6,800 mi.","$73,990",4.8
15,2018 Mercedes-Benz GLC 300 Base 4MATIC,"54,467 mi.","$29,151",4.5
16,2022 Mercedes-Benz AMG GLA 35 Base,"8,690 mi.","$49,736",4.5
17,2022 Mercedes-Benz GLB 250 Base,"8,158 mi.","$42,000",4.1
18,2022 Mercedes-Benz S-Class S 500 4MATIC,"8,401 mi.","$86,986",4.5
19,2020 Mercedes-Benz AMG S 63 Base 4MATIC,"24,958 mi.","$105,997",4.8
20,2021 Mercedes-Benz GLC 300 Base 4MATIC,"49,278 mi.","$37,280",4.2

### New TAsk

column1=MobileName
column2=Rating
column3=DiscountPrice
column4=ActualPrice
column5=Difference between discountprice and Actualprice

In [18]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

with open("flipkart.html","r",encoding="utf-8") as file:
    content = file.read()
soup = BeautifulSoup(content, 'html.parser')
MobileName = []
Rating = []
DiscountPrice = []
ActualPrice = []
products = soup.find_all('div', class_='_1AtVbE col-12-12')

for product in products:
    name = product.find('div', class_='_4rR01T')
    
    if name:
        disc = product.find('div', class_='_30jeq3 _1_WHN1')
        actual = product.find('div', class_='_3I9_wc _27UcVY')
        
        MobileName.append(name.text.strip())
        Rating.append(product.find('div', class_='_3LWZlK').text.strip())
        
        clean_disc = int(disc.text.replace('₹', '').replace(',', '').strip()) if disc else 0
        clean_actual = int(actual.text.replace('₹', '').replace(',', '').strip()) if actual else 0
        
        DiscountPrice.append(clean_disc)
        ActualPrice.append(clean_actual)

data = {
    "MobileName": MobileName,
    "Rating": Rating,
    "DiscountPrice": DiscountPrice,
    "ActualPrice": ActualPrice,
    "Difference": PriceDifference
}

df = pd.DataFrame(data)
df['Difference'] = df['ActualPrice'] - df['DiscountPrice']
df

,MobileName,Rating,DiscountPrice,ActualPrice,Difference
0,"Huawei P9 (Mystic Silver, 32 GB)",4.5,39999,40999,1000
1,"Huawei P9 (Prestige Gold, 32 GB)",4.5,39999,40999,1000
2,"SAMSUNG Galaxy S22 Plus 5G (Phantom Black, 128...",4.5,49999,101999,52000
3,"SAMSUNG Galaxy Z Flip3 5G (Phantom Black, 128 GB)",4.3,44999,95999,51000
4,"MOTOROLA Edge 30 Ultra (Interstellar Black, 25...",4.2,49999,74999,25000
5,"MOTOROLA Edge 30 Ultra (Starlight White, 256 GB)",4.2,49999,74999,25000
6,"SAMSUNG Galaxy A54 5G (Awesome Violet, 256 GB)",4.3,40999,45999,5000
7,"OnePlus 8 (Glacial Green, 256 GB)",4.5,46999,47999,1000
8,"SAMSUNG Galaxy S22 Plus 5G (Green, 128 GB)",4.5,49999,101999,52000
9,"OnePlus 8 (Interstellar Glow, 256 GB)",4.5,47349,47999,650
10,"Mi 10T Pro (Cosmic Black, 128 GB)",4.2,38849,47999,9150
11,"SAMSUNG Galaxy Z Flip3 5G (Cream, 128 GB)",4.3,44999,95999,51000
12,"vivo X70 Pro (Cosmic Black, 256 GB)",4.4,49999,57990,7991
13,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.4,47999,57990,9991
14,"OnePlus 9RT 5G (Hacker Black, 256 GB)",4.1,48999,0,-48999
15,"OnePlus 9RT 5G (Nano Silver, 256 GB)",4.1,46999,0,-46999
16,"OnePlus 9 5G (Winter Mist, 256 GB)",4,49999,0,-49999
17,"APPLE iPhone 11 (Red, 128 GB)",4.6,46999,48900,1901
18,"OnePlus 9 5G (Astral Black, 128 GB)",3.9,49999,0,-49999
19,"Xiaomi 12 Pro 5G (Opera Mauve, 256 GB)",4.2,43990,79990,36000
20,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.2,43900,79990,36090
21,"realme GT 2 Pro (Steel Black, 128 GB)",4.2,49999,57999,8000
22,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.5,48999,54990,5991
23,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.1,48880,84999,36119

## New TASK

make dataframe
column1=name of job
column2=name of company
column3=job location

In [22]:
import pandas as pd
from bs4 import BeautifulSoup

with open("indeed jobs.html", "r", encoding="utf-8") as file:
    content = file.read()
soup = BeautifulSoup(content, 'html.parser')

Job_name = []
Company_name = []
Location_job = []


jobs = soup.find_all('div', class_='cardOutline')

for job in jobs:

    Job_name.append(job.find('h2', class_='jobTitle').text.strip() if job.find('h2', class_='jobTitle') else "Null")
    Company_name.append(job.find('span', class_='css-1x7jm7c').text.strip() if job.find('span', class_='css-1x7jm7c') else "Null")
    Location_job.append(job.find('div', class_='css-659faq').text.strip() if job.find('div', class_='css-659faq') else "Null")

data = {
    "name of job": Job_name,
    "name of company": Company_name,
    "job location": Location_job
}

df = pd.DataFrame(data)
df

                        name of job name of company job location
0           Junior Python Developer            Null         Null
1                 AI & ML - Trainee            Null         Null
2          Python Developer Fresher            Null         Null
3            AI ML Python Developer            Null         Null
4                     Trainee AI ML            Null         Null
5                  Python Developer            Null         Null
6                       AI Engineer            Null         Null
7       Full Stack Developer Intern            Null         Null
8                      Data Analyst            Null         Null
9                  Python Developer            Null         Null
10  AI & ML Technologies Specialist            Null         Null
11                   AI/ML Engineer            Null         Null
12                 Python Developer            Null         Null
13                 Python Developer            Null         Null
14         Python Developer Fresher            Null         Null