In [ ]:
KNN

1)Read CSV file
2)Check Null Value
3)Define X & y
4)Split data Into train and test
5)Train KNN Model
6)Prediction
7)Model Evaluation
8)Assigning CM Values find TP,TN,FP,FN
9) Calculate Accuracy, Error Rate, Sensitivity, Specificit

In [1]:
# 1)
import pandas as pd
df = pd.read_csv('diabetes.csv')
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [2]:
# 2)
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [3]:
# 3)
y = df['Outcome']
X = df.drop(columns='Outcome')

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (768, 8)
y shape: (768,)

In [4]:
# 4)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training data size:", X_train.shape)
print("Testing data size:", X_test.shape)
print("Training data size:", y_train.shape)
print("Testing data size:", y_test.shape)

Training data size: (614, 8)
Testing data size: (154, 8)
Training data size: (614,)
Testing data size: (154,)

In [5]:
# 5)
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=25)
model=knn.fit(X_train, y_train)
model

KNeighborsClassifier(n_neighbors=25)

In [6]:
# 6)
y_pred = model.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0])

In [7]:
# 7)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
cm

array([[83, 16],
       [28, 27]])

In [8]:

# 8) 
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
TP = cm[1][1]

print("TN:", TN)
print("FP:", FP)
print("FN:", FN)
print("TP:", TP)

TN: 83
FP: 16
FN: 28
TP: 27

In [12]:
# 9) 
# Accuracy
accuracy = (TP + TN) / (TP + TN + FP + FN)
# Error Rate
error_rate = (FP + FN) / (TP + TN + FP + FN)
# error_rate = 1 - accuracy
# Sensitivity
sensitivity = TP / (TP + FN)
# Specificity
specificity = TN / (TN + FP)

print("Accuracy=", accuracy)
print("Error Rate=", error_rate)
print("Sensitivity=", sensitivity)
print("Specificity=", specificity)

Accuracy= 0.7142857142857143
Error Rate= 0.2857142857142857
Sensitivity= 0.4909090909090909
Specificity= 0.8383838383838383

In [14]:
# pregnancies=4, glucos=95, bloodpressure=55,skinthikness=30,insulin=180,BMI=29,DiabitisPredigreefunctio=0.5,age=51
prediction=model.predict( [[4, 95, 55, 30, 180, 29, 0.5, 51]]) 
prediction

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array([0])

## PB268

In [11]:
# 1)
import pandas as pd
df = pd.read_csv('data_breast_cancer.csv')
df

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

In [12]:
df.drop(columns=["id","Unnamed: 32"], inplace=True)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [13]:
# 2)
print(df.isna().sum())

diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [14]:
# 3) 
y = df['diagnosis']
X = df.drop(columns='diagnosis')

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (569, 30)
y shape: (569,)

In [20]:
# 4) 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (455, 30)
X_test shape: (114, 30)
y_train shape: (455,)
y_test shape: (114,)

In [21]:
# 5) 
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
model = knn.fit(X_train, y_train)

print("Model Trained successfully!")

Model Trained successfully!

In [22]:
# 6) 
y_pred = model.predict(X_test)
print("Predictions:", y_pred)

Predictions: ['B' 'M' 'M' 'B' 'B' 'M' 'M' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'M' 'B' 'B'
 'B' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B'
 'M' 'B' 'M' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'B' 'B'
 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'M' 'M'
 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'M' 'M' 'M' 'M' 'B' 'B'
 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'B' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'M'
 'B' 'B' 'M' 'B' 'B' 'M']

In [23]:
# 7) 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[71  0]
 [ 5 38]]

In [24]:
# 8) Assigning CM Values (Extracting TN, FP, FN, TP)
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
TP = cm[1][1]
print(f"TN: {TN}, FP: {FP}, FN: {FN}, TP: {TP}")

TN: 71, FP: 0, FN: 5, TP: 38

In [25]:
# 9) Calculate Performance Metrics
# Accuracy
accuracy = (TP + TN) / (TP + TN + FP + FN)
# Error Rate
error_rate = (FP + FN) / (TP + TN + FP + FN)
# Sensitivity (Recall)
sensitivity = TP / (TP + FN)
# Specificity
specificity = TN / (TN + FP)

print(f"Accuracy: {accuracy}")
print(f"Error Rate: {error_rate}")
print(f"Sensitivity: {sensitivity}")
print(f"Specificity: {specificity}")

Accuracy: 0.9561
Error Rate: 0.0439
Sensitivity: 0.8837
Specificity: 1.0000

## Example

In [28]:
# 1)
import pandas as pd
df = pd.read_csv('PlayTennis.csv')
df

     outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  mild     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  mild     high   True   no

In [32]:
df=pd.get_dummies(data=df, drop_first=True)
df

,windy,outlook_rainy,outlook_sunny,temp_hot,temp_mild,humidity_normal,play_yes
0,False,False,True,True,False,False,False
1,True,False,True,True,False,False,False
2,False,False,False,True,False,False,True
3,False,True,False,False,True,False,True
4,False,True,False,False,False,True,True
5,True,True,False,False,False,True,False
6,True,False,False,False,False,True,True
7,False,False,True,False,True,False,False
8,False,False,True,False,False,True,True
9,False,True,False,False,True,True,True
10,True,False,True,False,True,True,True
11,True,False,False,False,True,False,True
12,False,False,False,True,False,True,True
13,True,True,False,False,True,False,False

In [33]:
# 2)
print(df.isna().sum())

windy              0
outlook_rainy      0
outlook_sunny      0
temp_hot           0
temp_mild          0
humidity_normal    0
play_yes           0
dtype: int64

In [35]:
# 3)
y = df['play_yes']  
X = df.drop(columns='play_yes')
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (14, 6)
y shape: (14,)

In [36]:
# 4) 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (11, 6)
X_test shape: (3, 6)
y_train shape: (11,)
y_test shape: (3,)

In [39]:
# 5) 
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
model = knn.fit(X_train, y_train)
model

KNeighborsClassifier(n_neighbors=3)

In [40]:
# 6) 
y_pred = model.predict(X_test)
print("Predictions:", y_pred)

Predictions: [ True False  True]

In [41]:
# 7)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[0, 1],
       [1, 1]])

In [42]:
# 8)
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
TP = cm[1][1]
print(f"TN: {TN}, FP: {FP}, FN: {FN}, TP: {TP}")

TN: 0, FP: 1, FN: 1, TP: 1

In [44]:
# 9)
# Accuracy
accuracy = (TP + TN) / (TP + TN + FP + FN)
# Error Rate
error_rate = (FP + FN) / (TP + TN + FP + FN)
# Sensitivity (Recall)
sensitivity = TP / (TP + FN)
# Specificity
specificity = TN / (TN + FP)

print(f"Accuracy: {accuracy}")
print(f"Error Rate: {error_rate}")
print(f"Sensitivity: {sensitivity}")
print(f"Specificity: {specificity}")

Accuracy: 0.3333333333333333
Error Rate: 0.6666666666666666
Sensitivity: 0.5
Specificity: 0.0

In [46]:
prediction = model.predict([[1, 1, 0, 0, 0, 0]])
prediction

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array([False])

## Example

In [47]:
# 1)
import pandas as pd
df = pd.read_csv('Fish.csv')
df

    Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [49]:
# 2) Check Null Value
print(df.isna().sum())
print()
# 3) Define X & y
y = df['Species']
X = df.drop(columns='Species')
print("X shape:", X.shape)
print("y shape:", y.shape)
print()
# 4) Split data Into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)
print()
# 5) Train KNN Model
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=11)
model = knn.fit(X_train, y_train)
model 
print()
# 6) Prediction
y_pred = model.predict(X_test)
print("Predictions:", y_pred)
print()
# 7) Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

X shape: (159, 6)
y shape: (159,)

X_train shape: (127, 6)
X_test shape: (32, 6)
y_train shape: (127,)
y_test shape: (32,)


Predictions: ['Perch' 'Smelt' 'Roach' 'Perch' 'Roach' 'Perch' 'Smelt' 'Roach' 'Roach'
 'Perch' 'Bream' 'Perch' 'Bream' 'Roach' 'Bream' 'Perch' 'Perch' 'Perch'
 'Perch' 'Bream' 'Smelt' 'Bream' 'Bream' 'Bream' 'Perch' 'Perch' 'Roach'
 'Perch' 'Smelt' 'Smelt' 'Bream' 'Perch']

Confusion Matrix:
 [[7 0 3 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 6 0 3 0 0]
 [1 0 1 0 1 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 5 0]
 [0 0 3 0 0 0 0]]

In [51]:

prediction = model.predict([[85, 25.0, 20.0, 31, 6.0, 2.5]])
prediction

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array(['Perch'], dtype=object)

## Example

In [55]:
import pandas as pd
df = pd.read_csv('Iris.csv')
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
95,96,5.7,3.0,4.2,1.2,Iris-versicolor
96,97,5.7,2.9,4.2,1.3,Iris-versicolor
97,98,6.2,2.9,4.3,1.3,Iris-versicolor
98,99,5.1,2.5,3.0,1.1,Iris-versicolor
99,100,5.7,2.8,4.1,1.3,Iris-versicolor

In [56]:
df.drop(columns=['Id'], inplace=True)
df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [60]:
# 2) Check Null Value
print(df.isna().sum())
print()
# 3) Define X & y
y = df['Species']
X = df.drop(columns='Species')
print("X shape:", X.shape)
print("y shape:", y.shape)
print()
# 4) Split data Into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)
print()
# 5) Train KNN Model
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=9)
model = knn.fit(X_train, y_train)
model
print()
# 6) Prediction
y_pred = model.predict(X_test)
print("Predictions:", y_pred)
print()
# 7) Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)
print()
# 8)
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
TP = cm[1][1]
print(f"TN: {TN}, FP: {FP}, FN: {FN}, TP: {TP}")
print()
# 9)
# Accuracy
accuracy = (TP + TN) / (TP + TN + FP + FN)
# Error Rate
error_rate = (FP + FN) / (TP + TN + FP + FN)
# Sensitivity (Recall)
sensitivity = TP / (TP + FN)
# Specificity
specificity = TN / (TN + FP)

print(f"Accuracy: {accuracy}")
print(f"Error Rate: {error_rate}")
print(f"Sensitivity: {sensitivity}")
print(f"Specificity: {specificity}")

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

X shape: (100, 4)
y shape: (100,)

X_train shape: (80, 4)
X_test shape: (20, 4)
y_train shape: (80,)
y_test shape: (20,)


Predictions: ['Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa']

Confusion Matrix:
 [[12  0]
 [ 0  8]]

TN: 12, FP: 0, FN: 0, TP: 8

Accuracy: 1.0
Error Rate: 0.0
Sensitivity: 1.0
Specificity: 1.0

## PB230

In [62]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# a) Load the dataset
df = pd.read_csv('windpower - Copy.csv')
df

     Power (kW)  Wind speed (m/s)
0           0.0             0.000
1           0.0             0.125
2           0.0             0.150
3           0.0             0.225
4           0.0             0.275
..          ...               ...
495         0.0            24.775
496         0.0            24.850
497         0.0            24.875
498         0.0            24.950
499         0.0            25.000

[500 rows x 2 columns]

In [64]:
# b) Check and remove missing values permanently
df.dropna(inplace=True)
df

     Power (kW)  Wind speed (m/s)
0           0.0             0.000
1           0.0             0.125
2           0.0             0.150
3           0.0             0.225
4           0.0             0.275
..          ...               ...
495         0.0            24.775
496         0.0            24.850
497         0.0            24.875
498         0.0            24.950
499         0.0            25.000

[492 rows x 2 columns]

In [ ]:
# c) Define X  and y and Split
X = df[['Wind speed (m/s)']]
y = df['Power (kW)']
print("X shape:", X.shape)
print("y shape:", y.shape)
print()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)