In [ ]:
CH-4-Machine Learning-10Marks
------3 TOPICS---------
--> Simple Regression
--> Multiple Linear Regression
--> Polynomial Regression

CH-5-Classification Algorithm-12Marks
------2 TOPICS---------
--> KNN
--> Decision Tree

CH-6-Deep Learning -3Marks MCQ

multiple linear regression steps

1)Read CSV file
2)Check Null Value
3)Data Pre Processing 
4)Define X & y
5)Split data Into train and test
6)Create a model (lr.fit)
7)Find m & c
8)Find MSE,MAE,r2_score

## Mult Linier Regression

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
# 1)
df=pd.read_csv("car data.csv")
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [2]:
# 2)
df.isna().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [3]:
# 3)
df["Car_Age"]=2026-df["Year"]
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Car_Age
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0,12
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0,13
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0,9
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0,15
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0,12
...,...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0,10
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0,11
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0,17
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0,9
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0,10

In [4]:
#After step 3, if you don't need certain columns, just delete them as told
df.drop(columns="Year",inplace=True)
df

,Car_Name,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Car_Age
0,ritz,3.35,5.59,27000,Petrol,Dealer,Manual,0,12
1,sx4,4.75,9.54,43000,Diesel,Dealer,Manual,0,13
2,ciaz,7.25,9.85,6900,Petrol,Dealer,Manual,0,9
3,wagon r,2.85,4.15,5200,Petrol,Dealer,Manual,0,15
4,swift,4.60,6.87,42450,Diesel,Dealer,Manual,0,12
...,...,...,...,...,...,...,...,...,...
296,city,9.50,11.60,33988,Diesel,Dealer,Manual,0,10
297,brio,4.00,5.90,60000,Petrol,Dealer,Manual,0,11
298,city,3.35,11.00,87934,Petrol,Dealer,Manual,0,17
299,city,11.50,12.50,9000,Diesel,Dealer,Manual,0,9
300,brio,5.30,5.90,5464,Petrol,Dealer,Manual,0,10

In [5]:
df.drop(columns="Car_Name",inplace=True)
df

,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Car_Age
0,3.35,5.59,27000,Petrol,Dealer,Manual,0,12
1,4.75,9.54,43000,Diesel,Dealer,Manual,0,13
2,7.25,9.85,6900,Petrol,Dealer,Manual,0,9
3,2.85,4.15,5200,Petrol,Dealer,Manual,0,15
4,4.60,6.87,42450,Diesel,Dealer,Manual,0,12
...,...,...,...,...,...,...,...,...
296,9.50,11.60,33988,Diesel,Dealer,Manual,0,10
297,4.00,5.90,60000,Petrol,Dealer,Manual,0,11
298,3.35,11.00,87934,Petrol,Dealer,Manual,0,17
299,11.50,12.50,9000,Diesel,Dealer,Manual,0,9
300,5.30,5.90,5464,Petrol,Dealer,Manual,0,10

In [7]:
df = pd.get_dummies(data=df, drop_first=True)
df

,Selling_Price,Present_Price,Kms_Driven,Owner,Car_Age,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
0,3.35,5.59,27000,0,12,False,True,False,True
1,4.75,9.54,43000,0,13,True,False,False,True
2,7.25,9.85,6900,0,9,False,True,False,True
3,2.85,4.15,5200,0,15,False,True,False,True
4,4.60,6.87,42450,0,12,True,False,False,True
...,...,...,...,...,...,...,...,...,...
296,9.50,11.60,33988,0,10,True,False,False,True
297,4.00,5.90,60000,0,11,False,True,False,True
298,3.35,11.00,87934,0,17,False,True,False,True
299,11.50,12.50,9000,0,9,True,False,False,True
300,5.30,5.90,5464,0,10,False,True,False,True

In [8]:
# 4) 
y = df['Selling_Price']
X = df.drop(columns='Selling_Price')

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (301, 8)
y shape: (301,)

In [9]:
# 5)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training data size:", X_train.shape)
print("Testing data size:", X_test.shape)
print("Training data size:", y_train.shape)
print("Testing data size:", y_test.shape)

Training data size: (240, 8)
Testing data size: (61, 8)
Training data size: (240,)
Testing data size: (61,)

In [11]:
# 6)
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [15]:
# 7)
# 1. 'm' (Coefficients):
m = lr.coef_
print("Slopes (m):", m)
print()
# 2. 'c' (Intercept):
c = lr.intercept_
print("Intercept (c):", c)

Slopes (m): [ 4.29152503e-01 -6.15725866e-06 -9.03759824e-01 -3.53801365e-01
  2.53327258e+00  7.38464226e-01 -1.19059291e+00 -1.63902155e+00]

Intercept (c): 6.848642647119797

In [20]:
# car age=8 year ,petrol engine ,car 45000 chaleli che , manual che , indivisual vecheli che , owner 0 , present price  9lakh to aa klar ne hal vechva jay to ketli price aave 
i20_price=lr.predict([[9,45000,0,8,0,1,1,1]])
i20_price

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([5.51237738])

In [22]:
# present price 9.54 lakh, 43000 car chaleli , owner 0 ,age 13, desil car, manual car, deler 
new_car = lr.predict([[9.54, 43000, 0, 13, 1, 0, 0, 1]])
new_car

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([6.97282868])

In [27]:
# 8)

from sklearn.metrics import mean_squared_error,mean_absolute_error, r2_score
y_pred = lr.predict(X_test)
print("y_pred=",y_pred)
print()

y_pred= [ 2.95534303  8.178939    6.45427257 -1.42417501  9.08889914  7.41825441
  1.33644285  0.84027217  1.36501949  7.49026806  9.11830017  0.58573931
  8.41612774  3.42316502  6.90043281  3.04988309  0.48448171 10.70970753
  1.75207005  2.34571752  0.39746889  8.11925338  6.62469317  2.65939066
  0.78280554  3.69330765  5.24815462  2.82676351  2.13640446  1.75237686
  0.39730155  9.11750503 -0.66188053  2.29098014  8.57067341  4.4910324
  7.20530369  7.53824015  2.89101139  7.93588794  3.93585154  4.27133211
  4.33205704  0.6008847   7.34025071  0.47602539  7.29187681 11.23125597
  3.13805132  5.38262985  6.7988422   2.17888955 20.63303305 17.0015261
  7.50717349  9.69621308  4.47478116  8.97377615  1.82294639  7.60416734
  0.22226536]

In [28]:
# MSE
mse = mean_squared_error(y_test, y_pred)
print("MSE=",mse)
# MAE
mae = mean_absolute_error(y_test, y_pred)
print("MAE=",mae)
#r2_score
r2 = r2_score(y_test, y_pred)
print("r2_score=",r2)

MSE= 3.4788039706378613
MAE= 1.216225682129699
r2_score= 0.8489813024899084

### Example

In [29]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
# 1)
df=pd.read_csv("winequality.csv")
df
# 2)
df.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

In [30]:
# 4)
y = df['quality']
X = df.drop(columns='quality')

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (1143, 12)
y shape: (1143,)

In [31]:
# 5)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training data size:", X_train.shape)
print("Testing data size:", X_test.shape)
print("Training data size:", y_train.shape)
print("Testing data size:", y_test.shape)

Training data size: (914, 12)
Testing data size: (229, 12)
Training data size: (914,)
Testing data size: (229,)

In [32]:
# 6)
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [33]:
# 7)
# 1. 'm' (Coefficients):
m = lr.coef_
print("Slopes (m):", m)
print()
# 2. 'c' (Intercept):
c = lr.intercept_
print("Intercept (c):", c)

Slopes (m): [ 4.48281781e-02 -1.32650965e+00 -3.20227391e-01  4.64672501e-03
 -1.83692523e+00  2.78901313e-03 -2.58694082e-03 -3.27678330e+01
 -2.84072230e-01  9.53929276e-01  2.71613626e-01 -7.20729446e-05]

Intercept (c): 36.49622742033846

In [42]:
# 8)

from sklearn.metrics import mean_squared_error,mean_absolute_error, r2_score
y_pred = lr.predict(X_test)
print("y_pred=",y_pred)
print()
# MSE
mse = mean_squared_error(y_test, y_pred)
print("MSE=",mse)
# MAE
mae = mean_absolute_error(y_test, y_pred)
print("MAE=",mae)
#r2_score
r2 = r2_score(y_test, y_pred)
print("r2_score=",r2)

y_pred= [5.42239406 4.75039315 5.29684786 5.08885868 6.09486333 6.61357779
 5.4017609  5.12073623 5.80682335 5.32701664 6.34740954 6.36404342
 5.30874791 6.20726473 5.82424736 4.84564054 5.6866377  5.69867218
 5.46145685 6.40788444 6.03767614 6.03147727 5.20921387 6.48042456
 5.62504152 5.15767898 6.56630591 5.96162446 5.13243268 5.55393556
 6.22138034 5.50621416 6.61300256 5.72900211 5.57167536 5.30091294
 5.50270472 6.03438174 6.9574108  6.57721823 6.44071484 5.36204407
 7.11515613 5.3357927  5.02045693 5.1019234  5.66565116 5.86060262
 4.62611376 5.64639624 6.43111192 5.3070245  5.66220358 5.90248884
 5.7764028  6.40204632 5.49239433 5.66938259 6.05514973 5.22988268
 5.53032108 5.94808156 5.64622439 6.32047068 6.13819951 5.42307061
 6.88637688 5.23198061 4.89240584 5.94146638 5.72706586 5.36371717
 5.87330383 5.930108   5.20816681 5.18102988 5.84084001 5.87519663
 5.56537843 5.44033853 5.40608755 5.55643832 6.10128776 5.29822848
 5.49734983 6.03451096 5.34687089 5.6974897  5.72681184 5.29496201
 4.68397464 5.55695274 4.97804761 5.17647692 5.01828612 5.16874364
 5.33114803 6.62399797 5.93894188 5.60837069 5.69732096 6.37610023
 5.22035641 6.13830344 5.25352322 5.34490929 5.89277194 6.16666685
 5.58668514 6.56645076 5.98169489 5.29184041 5.4800231  6.0294004
 4.99093382 5.061652   5.33473638 6.42138353 5.7626642  4.82928225
 5.20620271 4.96992829 5.63039297 6.68734369 5.12155877 5.7081158
 5.74711888 5.73377378 4.98836899 6.34104493 5.09344585 4.92429433
 5.88902841 5.72761173 7.5251219  4.65411865 4.25272645 5.55340939
 5.54525202 5.73382194 6.99983494 5.34624769 5.6573963  4.87519337
 6.40987969 5.18446797 5.04901513 5.43076086 4.81623232 4.9340132
 6.58731777 5.42349931 6.33687426 5.33430743 5.91097736 5.67419869
 5.43068878 5.76187551 6.13328002 5.68231322 5.91201742 4.98545116
 5.7301566  5.6295802  5.76982625 5.350188   6.09995296 6.04911622
 5.60937534 5.2085794  6.52465666 5.36957031 5.43705669 5.63973057
 5.36744872 5.1815714  6.47092085 6.07255401 5.65482782 5.371954
 6.07147777 5.75435623 5.63932537 5.36143138 5.214711   5.56330047
 6.27852249 4.83213573 6.35160548 5.73281137 5.7290187  5.80131083
 6.55905346 5.82571986 5.54739967 5.46248875 5.04360668 6.57158693
 6.59359174 6.28008716 5.68938741 5.77881181 5.27959543 5.53932248
 5.88377579 5.50233434 5.217547   5.22908917 6.18210143 6.20384406
 5.1234562  6.12960094 5.50725131 5.67769048 5.50584127 5.10162049
 6.49869588 5.06768797 6.08294074 5.79419084 5.67068135 5.45333428
 5.0281772  5.74321052 4.8459337  6.13966888 5.36275274 5.47705627
 5.7460512 ]

MSE= 0.3824283521291962
MAE= 0.47997704397492197
r2_score= 0.31276385395082007

## PB226

In [54]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

df = pd.read_csv("RealEstate.csv")
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   No                                      414 non-null    int64
 1   X1 transaction date                     414 non-null    float64
 2   X2 house age                            414 non-null    float64
 3   X3 distance to the nearest MRT station  414 non-null    float64
 4   X4 number of convenience stores         414 non-null    int64
 5   X5 latitude                             414 non-null    float64
 6   X6 longitude                            414 non-null    float64
 7   Y house price of unit area              414 non-null    float64
dtypes: float64(6), int64(2)
memory usage: 26.0 KB
None

In [55]:
df.drop(columns=['No'], inplace=True)
df

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1
...,...,...,...,...,...,...,...
409,2013.000,13.7,4082.01500,0,24.94155,121.50381,15.4
410,2012.667,5.6,90.45606,9,24.97433,121.54310,50.0
411,2013.250,18.8,390.96960,7,24.97923,121.53986,40.6
412,2013.000,8.1,104.81010,5,24.96674,121.54067,52.5
413,2013.500,6.5,90.45606,9,24.97433,121.54310,63.9

In [56]:
print(df.isnull().sum())

X1 transaction date                       0
X2 house age                              0
X3 distance to the nearest MRT station    0
X4 number of convenience stores           0
X5 latitude                               0
X6 longitude                              0
Y house price of unit area                0
dtype: int64

In [57]:
y = df['Y house price of unit area']
X = df.drop(columns='Y house price of unit area')

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (414, 6)
y shape: (414,)

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=110)
print("Training data size:", X_train.shape)
print("Testing data size:", X_test.shape)
print("Training data size:", y_train.shape)
print("Testing data size:", y_test.shape)

Training data size: (289, 6)
Testing data size: (125, 6)
Training data size: (289,)
Testing data size: (125,)

In [59]:
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [60]:
y_pred = lr.predict(X_test)
print(y_pred)

[40.06913335 32.56470479 29.80668902 44.60809493 39.96541473 44.34984726
 37.64834639 51.18801909 37.08044432 38.64449437 36.45757424 31.64776451
 43.03392987 16.64984039 36.61381207 31.21699197 39.55333345 41.89770923
 46.41953538 42.69067202 40.49560609 53.3447345  40.74436408 36.67049204
 46.86499408 42.78349352 47.25115307 40.53653503 42.57499139 50.88772177
 44.81813044 41.05114011 35.39386877 42.95199941 13.97578058 30.00463214
  0.32863779 39.56884707 47.9626967  34.0147913  40.23322474 49.74492584
 36.73990519 35.39784888 29.6071314  45.83432319 42.44745248 37.88237609
 31.55675944 47.517238   35.03089266 45.17666152 45.98711652 47.32685806
 54.18178829 15.18888047 43.78264851 44.75385635 37.69057227 39.34215811
 44.21812376 44.27270068 47.84570949 38.42626454 41.0626191  19.64522484
 47.9626967  43.85961508 37.99756745 43.80152052 42.39390912 42.57768877
 44.73329588 32.31758114 46.89135756 38.92015239 40.90438603 43.95669962
 34.28075691 25.5851042  16.26403643 45.66098257 42.05300968 10.81561309
 31.65043887 49.10789869 47.40016786 13.5604683  46.02203009 44.82145569
 34.76747867 35.40469328 31.48202917 45.59192922 42.0246353  42.54274755
 14.70678074 43.68554348 27.69149444 43.0460661  27.63908623 35.23545719
 45.89665228 50.31290226 42.86214486 44.61671482 49.59887911 32.11577476
 31.86965512 38.39003281 44.58865137 25.50284004 46.20113858 37.45131001
 14.70678074 44.2357441   9.25548578 37.23816575 38.97851394 47.40016786
 39.50115693 32.15412829 46.99435489 47.07907957 53.12308545]

In [62]:
mse = mean_squared_error(y_test, y_pred)
mse

77.14802598253691

## EXAMPLE

In [65]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

df = pd.read_csv("insurance.csv")
df

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [67]:
df = pd.get_dummies(df, drop_first=True)
df

,age,bmi,children,expenses,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.9,0,16884.92,False,True,False,False,True
1,18,33.8,1,1725.55,True,False,False,True,False
2,28,33.0,3,4449.46,True,False,False,True,False
3,33,22.7,0,21984.47,True,False,True,False,False
4,32,28.9,0,3866.86,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...
1333,50,31.0,3,10600.55,True,False,True,False,False
1334,18,31.9,0,2205.98,False,False,False,False,False
1335,18,36.9,0,1629.83,False,False,False,True,False
1336,21,25.8,0,2007.95,False,False,False,False,True
1337,61,29.1,0,29141.36,False,True,True,False,False

In [70]:
X = df.drop(columns=['expenses'])
y = df['expenses']

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (1338, 8)
y shape: (1338,)

In [71]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("Training data size:", X_train.shape)
print("Testing data size:", X_test.shape)
print("Training data size:", y_train.shape)
print("Testing data size:", y_test.shape)

Training data size: (1070, 8)
Testing data size: (268, 8)
Training data size: (1070,)
Testing data size: (268,)

In [72]:
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [74]:
y_pred = lr.predict(X_test)
y_pred

array([ 8976.76760964,  7061.47078348, 36861.00837958,  9439.16742899,
       26965.82783567, 10866.56613365,   163.68342867, 16902.1625389 ,
        1092.78891435, 11221.84972563, 28100.81510083,  9381.37647426,
        5265.11298425, 38433.51445836, 40248.06655201, 37084.37888675,
       15248.12984097, 35901.53286407,  9127.45708271, 31464.93323459,
        3848.37001706, 10130.91497172,  2370.69195712,  7139.66129952,
       11294.96254187, 12967.62453886, 14509.58195129,  6160.69986604,
        9962.85959031,  2163.07205222,  9116.85372521, 13064.63457975,
        4571.36274084,  3423.94442545,  4460.1164586 , 13031.12862237,
        1979.67910034,  8813.16035987, 33258.81811961, 32584.31750912,
        3910.32992482,  4343.38905053, 14143.48952085, 11435.21647816,
        8791.14158849, 12096.4844327 ,  5272.59144805,  3150.51559564,
       35504.10915377,  9154.13549953, 15835.69309292,  2352.62339682,
       12359.83078765,  1472.69854255, 13377.66583865, 12570.20082856,
        4353.80717022, 32169.40215637, 13321.12708687, 12913.03146333,
       14167.45396849, 10500.87520372, 16362.21376975,  7768.13192586,
       11846.62396902,  4048.65144585, 26652.30575772, 10928.59434504,
        2131.06056004,  6210.73023862, 10747.44530612, 11628.35102671,
       10969.53928486,  9152.42718896, 11967.74015271,  6739.34476548,
        7254.49087711, 10750.3226356 ,  6580.52140858,  8761.81484345,
        3756.25268416, 36631.43593705,  6378.55903609, 30852.67074621,
       34855.45770807, 35268.04893756,  7029.37489999, 12869.4743934 ,
        9947.53528083, 14475.20183193, 17695.82091826, 35257.25076445,
       33018.89478037,  6170.31597396, 32015.81251502,  9482.09446397,
       29431.68339254,  3673.59098299, 28322.16117746,  5833.8465128 ,
        5405.74204674,  1883.30448844, 11513.22813965, 15077.43397333,
       11712.3532568 ,  4308.7979398 ,  9897.5726287 , 31703.94537845,
         -78.75023292, 32822.64944067,  3281.32493403, 10175.61325817,
       14319.90830978, 31634.64185265, 11467.67031952,  3930.19512167,
       13108.02751486, 31809.84532433,  8151.1278017 ,  3251.2591181 ,
        8456.50961256, 10595.5537768 , 15227.44276728,  5660.98235091,
        3766.02272835, 10243.07489729, 10886.12525182, 11111.87910589,
       14436.87063556,  7427.65522919,  5374.24945541,  9224.78767332,
        9357.30039506, 12543.74115369,  8337.78241857, 15334.29057281,
        8396.20833548, 31796.0827337 , 35802.8740163 , 31608.86973463,
        6015.92921741, 12601.48242852,  6006.25853302, 14553.58493031,
        2477.76928633, 32962.06271912,  6280.1872339 ,  5034.23029445,
       14351.27172646,  6941.35582863, 38684.13168368,  3080.22751421,
        5873.05825442, 31675.57169734, 11576.10169074,  8484.5285583 ,
       14802.38958868,  9822.86595681, 27100.67447318, 33461.40219328,
       14543.18680167,  1668.59351769, 13166.08980621,  2217.8439823 ,
        5451.16430895, 11575.92528416, 39807.66796095, 36512.58399817,
       34017.04596833,  3897.22030625,  7454.3614484 ,  8662.24235234,
       12467.48013815,  4800.999583  ,  2047.08371503, 32105.57262657,
       25110.3712824 , 17490.6694978 , 26420.53003011, 10164.09991257,
       37244.18310997,  -448.89716146,  6787.48465212,  7782.18832343,
        4361.96091911,  5090.99513272,  5905.30562559,  4305.09427307,
       15185.48237636, 11115.66273417,  6935.15878984,  2536.75984934,
        1540.95484891, 31945.66021231, 16403.39607525, 12010.22434106,
        1263.86775018, 12537.27569304,  1558.67257785,  8735.94336562,
        1861.19370179, 33927.65286391, 10853.35408323,  2615.34950932,
       25658.46152867, 26356.96892216,  9426.15717023,  1806.74966597,
       13278.19270735,  1118.78268909, 10384.35495004, 10571.15959585,
       16957.24029897, 26857.2176099 ,  6947.30139587,  5181.77844596,
        5854.48390659, 13217.98586285, 11085.02183452,  8358.29751543,
        5129.57878989, 12302.67770987, 13853.41156161, 35786.73787126,
        4153.83770593, 28922.57830394,  -916.04873686,  2877.06261868,
       11034.53293699, 15694.68682476,  5227.38594598,  6902.27964492,
        3853.87949901, 31311.04145254,  7226.68989879, 12422.15280597,
        5628.21852686,  9528.58347052, 36324.02604042,  4438.80033919,
        9652.65108441, 31161.9311154 ,  5752.67685952,  4595.42654828,
        1055.79666487,  4844.39007014,  4575.01081121,  6507.7594237 ,
       18678.73488478, -1541.19367668,  2376.35047877, 10696.32144642,
        3150.36655593, 10197.14195097,  3725.94950255,  5114.19497673,
       12399.97907843,  6214.39156999,  8224.15597786,  7592.56436181,
        8927.76583277, 10483.65365656, 27822.44366233, 39062.75988688,
       11770.14176356,  7678.27490248, 40917.11511104, 12319.07536774])

In [75]:
y_pred1 = lr.predict([[31,21.5,2,0,1,0,0,0]])
y_pred1

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([27781.79203199])